### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by Amir-Pourhadi** [ari3223/Avin#1]
**Are you joking? Really you made a repository for this? 🤣** 
Come on, Is it not better to be friendly with newbies? 😄

@ari3223

**Comment by ari3223** [comment]
> **Are you joking? Really you made a repository for this? 🤣** 
> Come on, Is it not better to be friendly with newbies? 😄
> 
> @ari3223 

I'm sorry man i have to do it❤️❤️❤️ keep going never give up 💪

**Comment by Amir-Pourhadi** [comment]
Thanks, dude ❤️  Wishing you the best for every step in your journey.
